### ISSUE TITLE
Use OutFLANK with sliding-windows calculated Fst values

### ISSUE THREAD

**Issue by Yung-Chien** [whitlock/OutFLANK#24]
Hi @DrK-Lo , @casalott and @whitlock ,
I'd like to find outlier of my Fst calculated by sliding-windows , and an issue appears that a window include many genotypes of many snps,  it's hardly to difine a value like 0,1 or 2 to generate an input file for OutFLANK. So how could I create this input file?
Thanks in advances,
Yung

**Comment by whitlock** [comment]
Hi Yung,

OutFLANK isn’t designed (or suitable) for use on Fst calculated from sliding windows.  The distribution of Fst from sliding windows is not a chi square as assumed by OutFLANK. So unfortunately I’d say it is unwise to try to use it for this case.

Michael Whitlock
Department of Zoology
University of British Columbia
6270 University Blvd.
Vancouver, BC V6T1Z4 Canada
