### ISSUE TITLE
Failed to install in higher version R

### ISSUE THREAD

**Issue by ChenJuiYANG** [whitlock/OutFLANK#35]
To install the package OutFLAND, the manual uses the "biocLite". 
However, the "biocLite" is not supported for newer version R.  
An error message returned as follow: 

" _Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install_ "

And after installed BioManager, it said 

" _package ‘OutFLANK’ is not available for Bioconductor version '3.18'_ "

(older version BioManager is not working as well, unfortunately)

Is there any other method to install the package other than downgrade R to a lower version? 
Or, do you have a plan to update OutFLAND? 

Thanks, 
CJ

**Comment by DrK-Lo** [comment]
I am using R 4.3.1 and the following code works for install:

install.packages("devtools")
if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")

BiocManager::install("qvalue", force=TRUE)
devtools::install_github("whitlock/OutFLANK", force=TRUE)

**Comment by ChenJuiYANG** [comment]
Thank you so much! It worked! 

CJ
